name = "Kosaraju"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Kosaraju"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Kosaraju"

[[lean_lib]]
name = "Tarjan"

[[lean_lib]]
name = "Graph"

[[lean_lib]]
name = "ListHelper"
